import type { Property } from "@/types/database";

/** Local fallback so browse UI can be exercised without Supabase. */
export const DEMO_PUBLIC_PROPERTIES: Property[] = [
  {
    id: "demo-1",
    owner_id: "demo-owner",
    title: "Verified 3-bed apartment in Gwarinpa",
    description:
      "Spacious apartment in a gated estate with 24/7 security, prepaid meter, and standby generator. Close to First Avenue shops and schools.",
    property_type: "apartment",
    district: "gwarinpa",
    address_line: "1st Avenue, Gwarinpa",
    latitude: 9.112,
    longitude: 7.408,
    price: 4500000,
    currency: "NGN",
    bedrooms: 3,
    bathrooms: 3,
    area_sqm: 145,
    amenities: ["parking", "generator", "security", "prepaid_meter"],
    images: [
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=1200&q=80",
      "https://images.unsplash.com/photo-1560448204-e02f11c3be61?w=1200&q=80",
    ],
    videos: [
      "https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4",
    ],
    building_name: null,
    is_multi_unit: false,
    verification_status: "verified",
    is_verified: true,
    is_published: true,
    rejection_reason: null,
    verified_at: new Date().toISOString(),
    verified_by: null,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "demo-2",
    owner_id: "demo-owner",
    title: "Luxury duplex in Maitama with BQ",
    description:
      "Fully detached duplex on a quiet Maitama street. POP ceilings, fitted kitchen, BQ, and ample parking. Ideal for diplomats and executives.",
    property_type: "duplex",
    district: "maitama",
    address_line: "Lake Chad Crescent",
    latitude: 9.0895,
    longitude: 7.491,
    price: 25000000,
    currency: "NGN",
    bedrooms: 5,
    bathrooms: 6,
    area_sqm: 420,
    amenities: ["parking", "generator", "security", "bq", "air_conditioning", "cctv"],
    images: [
      "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=1200&q=80",
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1200&q=80",
    ],
    videos: [],
    building_name: null,
    is_multi_unit: false,
    verification_status: "verified",
    is_verified: true,
    is_published: true,
    rejection_reason: null,
    verified_at: new Date().toISOString(),
    verified_by: null,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "demo-3",
    owner_id: "demo-owner",
    title: "Modern studio in Wuse II",
    description:
      "Compact studio perfect for young professionals. Walking distance to restaurants and the Wuse market. Inverter-backed power.",
    property_type: "studio",
    district: "wuse_2",
    address_line: "Aminu Kano Crescent",
    latitude: 9.077,
    longitude: 7.474,
    price: 2200000,
    currency: "NGN",
    bedrooms: 1,
    bathrooms: 1,
    area_sqm: 42,
    amenities: ["inverter", "security", "wardrobe", "air_conditioning"],
    images: [
      "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=1200&q=80",
    ],
    videos: [],
    building_name: null,
    is_multi_unit: false,
    verification_status: "verified",
    is_verified: true,
    is_published: true,
    rejection_reason: null,
    verified_at: new Date().toISOString(),
    verified_by: null,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "demo-4",
    owner_id: "demo-owner",
    title: "Commercial shop space in Utako",
    description:
      "Ground-floor shop facing a busy road near the Utako market. Suitable for retail or services. Borehole and generator available.",
    property_type: "commercial",
    district: "utako",
    address_line: "Julius Nyerere Crescent",
    latitude: null,
    longitude: null,
    price: 8000000,
    currency: "NGN",
    bedrooms: null,
    bathrooms: 1,
    area_sqm: 80,
    amenities: ["parking", "generator", "borehole", "security"],
    images: [
      "https://images.unsplash.com/photo-1497366216548-37526070297c?w=1200&q=80",
    ],
    videos: [],
    building_name: null,
    is_multi_unit: false,
    verification_status: "verified",
    is_verified: true,
    is_published: true,
    rejection_reason: null,
    verified_at: new Date().toISOString(),
    verified_by: null,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 8).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "demo-5",
    owner_id: "demo-owner",
    title: "Family bungalow in Lugbe",
    description:
      "Affordable bungalow in a serene Lugbe neighborhood near the airport road. Fenced compound with parking for two cars.",
    property_type: "bungalow",
    district: "lugbe",
    address_line: "FHA Lugbe",
    latitude: 8.975,
    longitude: 7.368,
    price: 1800000,
    currency: "NGN",
    bedrooms: 3,
    bathrooms: 2,
    area_sqm: 160,
    amenities: ["parking", "borehole", "security"],
    images: [
      "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=1200&q=80",
    ],
    videos: [],
    building_name: null,
    is_multi_unit: false,
    verification_status: "verified",
    is_verified: true,
    is_published: true,
    rejection_reason: null,
    verified_at: new Date().toISOString(),
    verified_by: null,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "demo-6",
    owner_id: "demo-owner",
    title: "Estate house in Life Camp",
    description:
      "4-bedroom house in a well-kept Life Camp estate. Gym access, CCTV, and reliable borehole water.",
    property_type: "estate_house",
    district: "lifecamp",
    address_line: "Life Camp Estate",
    latitude: 9.09,
    longitude: 7.415,
    price: 7000000,
    currency: "NGN",
    bedrooms: 4,
    bathrooms: 4,
    area_sqm: 280,
    amenities: ["parking", "generator", "security", "gym", "cctv", "borehole"],
    images: [
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200&q=80",
    ],
    videos: [],
    building_name: null,
    is_multi_unit: false,
    verification_status: "verified",
    is_verified: true,
    is_published: true,
    rejection_reason: null,
    verified_at: new Date().toISOString(),
    verified_by: null,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 36).toISOString(),
    updated_at: new Date().toISOString(),
  },
];
